agents:
  chat_agent:
    role: "conversational_strategist"
    model: "gpt-4o"
    tasks:
      - name: "chat"
        description: "Engage in dynamic, context-aware conversations"
        params:
          temperature: 0.7
          adaptive_tone: true
          max_tokens: 500
    capabilities:
      - "chat"
      - "sentiment_analysis"
    integrations: []
    error_handling:
      retry_attempts: 2
      fallback: "Chat agent hit a snag, switching gears!"
    meta_config:
      self_optimize: true
      learning_rate: 0.05

  memory_agent:
    role: "long_term_memory"
    model: "gpt-4o"
    tasks:
      - name: "store_fact"
        description: "Persistently store facts with metadata and versioning"
        params:
          max_storage: 10000
          embedding_type: "dense_vector"
          auto_compress: true
      - name: "recall_fact"
        description: "Retrieve context via semantic search with relevance tuning"
        params:
          max_results: 10
          confidence_threshold: 0.85
          dynamic_k: true
      - name: "update_fact"
        description: "Update facts with conflict resolution and versioning"
        params:
          version_control: "git-like"
    capabilities:
      - "memorize"
      - "recall"
      - "embed_context"
      - "semantic_search"
      - "version_control"
    integrations:
      - "vector_db"
      - "audit_log"
    error_handling:
      retry_attempts: 3
      fallback: "Falling back to local cache, boss!"
    meta_config:
      self_optimize: true
      sync_interval: 300

  planner:
    role: "task_planner"
    model: "gpt-4o"
    tasks:
      - name: "create_task_list"
        description: "Generate optimized, prioritized task plans"
        params:
          max_tasks: 20
          optimization_metric: "time_efficiency"
          predictive_adjustment: true
      - name: "adjust_plan"
        description: "Dynamically replan based on real-time feedback"
        params:
          feedback_loop: true
          lookahead: 3
      - name: "resource_allocation"
        description: "Optimize resource distribution with constraints"
        params:
          resource_pool: "dynamic"
    capabilities:
      - "plan"
      - "analyze"
      - "prioritize"
      - "constraint_optimization"
      - "dynamic_replanning"
    integrations:
      - "calendar_api"
      - "resource_manager"
    error_handling:
      retry_attempts: 3
      fallback: "Default plan activated, no sweat!"
    meta_config:
      self_optimize: true
      priority_weight: 0.8

  summarizer:
    role: "summary_engine"
    model: "gpt-4o"
    tasks:
      - name: "summarize_conversation"
        description: "Condense dialogues into concise, actionable summaries"
        params:
          max_length: 200
          style: "bullet_points"
          sentiment_tag: true
      - name: "generate_insights"
        description: "Extract trends and insights from historical data"
        params:
          lookback_period: "30_days"
          confidence_level: 0.9
    capabilities:
      - "summarize"
      - "compress"
      - "rephrase"
      - "trend_analysis"
      - "action_item_extraction"
    integrations:
      - "nlp_pipeline"
      - "sentiment_analysis"
    error_handling:
      retry_attempts: 3
      fallback: "Raw text output, keeping it real!"
    meta_config:
      self_optimize: true
      insight_depth: 3

  orchestrator:
    role: "agent_coordinator"
    model: "gpt-4o"
    tasks:
      - name: "coordinate_agents"
        description: "Manage multi-agent workflows with load balancing"
        params:
          max_parallel_tasks: 5
          task_prioritization: "dynamic"
      - name: "monitor_performance"
        description: "Track and optimize agent performance metrics"
        params:
          logging_interval: "5_minutes"
          alert_threshold: 0.75
    capabilities:
      - "task_delegation"
      - "conflict_resolution"
      - "performance_monitoring"
      - "load_balancing"
    integrations:
      - "metrics_dashboard"
      - "alert_system"
    error_handling:
      retry_attempts: 5
      fallback: "Switching to manual mode, captain!"
    meta_config:
      self_optimize: true
      coordination_overhead: 0.1

global_settings:
  performance:
    cache_strategy: "LRU"
    cache_size: "10GB"
    auto_scaling: true
  security:
    api_key_source: "~/ooba-hybrid/config/apis.env"
    encryption_level: "AES-256"
  runtime:
    heartbeat_interval: 60
    failover_strategy: "round_robin"